import pytest
import os
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient
from app import app, get_hf_token

client = TestClient(app)
USER_ID = "11111111-1111-4111-a111-111111111111"

def mock_supabase_auth(token: str):
    if token == USER_ID:
        user_mock = MagicMock()
        user_mock.id = USER_ID
        res_mock = MagicMock()
        res_mock.user = user_mock
        return res_mock
    raise Exception("Invalid token")

class TestHFTokenDetection:

    def test_get_hf_token_trims_whitespace_safely(self):
        with patch.dict(os.environ, {"HF_TOKEN": "  hf_test_token_123  "}):
            token = get_hf_token()
            assert token == "hf_test_token_123"

    @patch("app.db")
    @patch("requests.post")
    def test_hf_token_present_enables_llm_generation(self, mock_requests_post, mock_db):
        mock_db.auth.get_user.side_effect = mock_supabase_auth
        
        mock_rpc = MagicMock()
        mock_rpc.execute.return_value.data = [
            {"id": "s1", "repo_name": "repo1", "file_path": "main.py", "language": "python", "code_content": "def main(): pass", "source_url": "http://example.com", "repository_id": "r1", "index_version": "v1"}
        ]
        mock_db.rpc.return_value = mock_rpc

        mock_kw = MagicMock()
        mock_kw.eq.return_value.ilike.return_value.limit.return_value.execute.return_value.data = []
        mock_db.table.return_value.select.return_value.eq.return_value = mock_kw

        mock_res = MagicMock()
        mock_res.status_code = 200
        mock_res.json.return_value = {
            "choices": [{"message": {"content": "This is a grounded answer generated by Llama."}}]
        }
        mock_requests_post.return_value = mock_res

        with patch.dict(os.environ, {"HF_TOKEN": "  hf_mock_secret_token  "}):
            response = client.post(
                "/search",
                headers={"Authorization": f"Bearer {USER_ID}"},
                json={"query": "unique test query for enabled token generation 101"}
            )
            assert response.status_code == 200
            data = response.json()
            assert "grounded answer generated by Llama" in data["answer"]
            assert "configure HF_TOKEN" not in data["answer"]
            assert "hf_mock_secret_token" not in str(data)

    @patch("app.db")
    def test_hf_token_missing_returns_retrieval_fallback(self, mock_db):
        mock_db.auth.get_user.side_effect = mock_supabase_auth

        mock_rpc = MagicMock()
        mock_rpc.execute.return_value.data = [
            {"id": "s2", "repo_name": "repo1", "file_path": "main.py", "language": "python", "code_content": "def main(): pass", "source_url": "http://example.com", "repository_id": "r1", "index_version": "v1"}
        ]
        mock_db.rpc.return_value = mock_rpc

        mock_kw = MagicMock()
        mock_kw.eq.return_value.ilike.return_value.limit.return_value.execute.return_value.data = []
        mock_db.table.return_value.select.return_value.eq.return_value = mock_kw

        with patch.dict(os.environ, {}, clear=True):
            response = client.post(
                "/search",
                headers={"Authorization": f"Bearer {USER_ID}"},
                json={"query": "unique test query for missing token fallback 102"}
            )
            assert response.status_code == 200
            data = response.json()
            assert "configure HF_TOKEN in your environment settings" in data["answer"]
            assert len(data["sources"]) > 0

    @patch("app.db")
    @patch("requests.post")
    def test_inference_failure_with_token_present_preserves_sources_without_claiming_missing_token(self, mock_requests_post, mock_db):
        mock_db.auth.get_user.side_effect = mock_supabase_auth

        mock_rpc = MagicMock()
        mock_rpc.execute.return_value.data = [
            {"id": "s3", "repo_name": "repo1", "file_path": "main.py", "language": "python", "code_content": "def main(): pass", "source_url": "http://example.com", "repository_id": "r1", "index_version": "v1"}
        ]
        mock_db.rpc.return_value = mock_rpc

        mock_kw = MagicMock()
        mock_kw.eq.return_value.ilike.return_value.limit.return_value.execute.return_value.data = []
        mock_db.table.return_value.select.return_value.eq.return_value = mock_kw

        mock_res = MagicMock()
        mock_res.status_code = 503
        mock_res.text = "Model loading"
        mock_requests_post.return_value = mock_res

        with patch.dict(os.environ, {"HF_TOKEN": "hf_active_secret_token"}):
            response = client.post(
                "/search",
                headers={"Authorization": f"Bearer {USER_ID}"},
                json={"query": "unique test query for inference failure 103"}
            )
            assert response.status_code == 200
            data = response.json()
            assert len(data["sources"]) > 0
            assert "currently unavailable" in data["answer"]
            assert "configure HF_TOKEN" not in data["answer"]
            assert "hf_active_secret_token" not in str(data)

    @patch("app.db")
    @patch("requests.post")
    def test_read_timeout_falls_back_resiliently(self, mock_requests_post, mock_db):
        import requests
        mock_db.auth.get_user.side_effect = mock_supabase_auth

        mock_rpc = MagicMock()
        mock_rpc.execute.return_value.data = [
            {"id": "s4", "repo_name": "repo1", "file_path": "main.py", "language": "python", "code_content": "def main(): pass", "source_url": "http://example.com", "repository_id": "r1", "index_version": "v1"}
        ]
        mock_db.rpc.return_value = mock_rpc

        mock_kw = MagicMock()
        mock_kw.eq.return_value.ilike.return_value.limit.return_value.execute.return_value.data = []
        mock_db.table.return_value.select.return_value.eq.return_value = mock_kw

        # Simulate ReadTimeout for Llama model request
        mock_requests_post.side_effect = requests.exceptions.ReadTimeout("Read timed out")

        with patch.dict(os.environ, {"HF_TOKEN": "hf_timeout_test_token"}):
            response = client.post(
                "/search",
                headers={"Authorization": f"Bearer {USER_ID}"},
                json={"query": "unique test query for single Llama timeout 105"}
            )
            assert response.status_code == 200
            data = response.json()
            assert "timed out" in data["answer"]
            assert len(data["sources"]) > 0
            assert "configure HF_TOKEN" not in data["answer"]

